const SampleCategories = [
    "Technology",
    "Programming",
    "Web Development",
    "Mobile Development",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Cybersecurity",
    "Cloud Computing",
    "DevOps",
    "Design",
    "Startups",
    "Productivity",
    "Education",
    "Health & Fitness",
    "Travel",
    "Finance",
    "Marketing",
    "Career & Jobs",
    "Personal Development"
];
const SampleTags = [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Prisma",
    "Drizzle ORM",
    "Docker",
    "Kubernetes",
    "AWS",
    "Firebase",
    "UI/UX",
    "Open Source",
    "Blockchain",
    "Web3",
    "AR/VR",
    "ChatGPT",
    "LLMs",
    "Data Visualization"
];
export { SampleCategories, SampleTags };